config/routes.rb
Rails.application.routes.draw do
  get 'basics/quotations'
  get 'basics/fetch'

  root :to => "basics#quotations"
  root :to  => "basics#quotations"
  root :to => "basics#quotations.json"
  post 'basics/quotations'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quotation.rb
class Quotation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/basics_controller.rb
require 'nokogiri'
require 'rubygems'
require 'open-uri'
class BasicsController < ApplicationController
  def quotations
    if params[:quotation]
      @quotation = Quotation.new(basic_params)
      if @quotation.save
        flash[:notice] = 'Quotation was successfully created.'
        @quotation = Quotation.new

      end
    else
      @quotation = Quotation.new
    end
    if params[:sort_by] == "date"
      @quotations = Quotation.order(:created_at)
    else
      @quotations = Quotation.order(:category)
    end

    @quotations = Quotation.all
    respond_to do |format|
      format.html
      format.json {render json: @quotations }
      format.xml { render xml: @quotations }
    end

  end
  def basic_params
    if params[:category] != 'new'
      params.require(:quotation).permit(:author_name, :category, :quote )
    else if param[:category] == 'new'
           params.require(:quotation).permit(:author_name, :new_field, :quote )
         end
    end
  end
  def fetch

    xml = open(params["qxml"])
    doc = Nokogiri::XML(xml)
    doc.css("quotation").each do |node|
      children = node.children

      @quotation = Quotation.create(
                 :author_name => children.css('author_name').inner_text,
                 :category => children.css('category').inner_text,
                 :quote => children.css('quote').inner_text
    )
    end
    @quotation.save
    redirect_to basics_quotations_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/views/basics/quotations.html.erb
<h1>Basics#quotations</h1>
<p>Find me in app/views/basics/quotations.html.erb</p>
<h3>Quotations</h3>
  <%= form_tag basics_fetch_path, method: :get do %>
      <p><%= label_tag(:qxml, "enter url") %></p>        
      <p><%= text_field_tag :qxml %></p>
      <%= submit_tag 'import' %>                         
                                                         
  <% end %>                                              
                                                         
<ul>
  <% for quotation in @quotations %>
      <li><%= h quotation.author_name %>:<%= quotation.category %> <%= h quotation.quote %></li>
  <% end %>
</ul>


<br/>
<% if params[:sort_by] == "date" %>
    <%= link_to "Sort by category", :action => :quotations, :sort_by => :category %>
<% else %>
    <%= link_to "Sort by date", :action => :quotations, :sort_by => :date %><br>

    <!--  <%= link_to "Export Quotations as XML", "basics/quotations.xml" %><br>
    <%= link_to "Export Quotations as JSON", "basics/quotations.json" %> -->


    <hr/>
    <a href="/basics/quotations.xml">Export Quotations as XML</a>
    <br/>
    <a href="/basics/quotations.json">Export Quotations as JSON</a>

<% end %>
<hr/>
<h3>New quotation</h3>
 <%= form_for @quotation, :url => { :action => :quotations } do |form| %>

    <!-- Submit the form to action 'edit' in the controller -->










      <fieldset>
        <legend>Enter details</legend>
        <div class="form_row">
          <%= form.label :author_name %>
          <%= form.text_field :author_name, :size => 20, :maxlength => 40 %>
        </div>
        <div class="form_row">
             <%= form.label :category %>
           <%= form.text_field :category, :size => 20, :maxlength => 40 %>
          <label for="quotation_category">Category</label>
          <select id="selector" name="quotation[category]">
            <option selected="selected" value="Inspirational">Inspirational</option>
            <option value="Education">Education</option>
            <option value="Food">Food</option>
            <option value="Abstract">Abstract</option>
            <option value="New Category">New Category</option>
          </select>
        </div>
        <div class="form_row" id="action_div">
          <label for="quotation_new_category">New category</label>
          <textarea name="new_category" id="action_text" require="required">
        </textarea>
        </div>
        <div class="form_row">
          <%= form.label :quote %>
          <%= form.text_area :quote, :rows => 2, :cols => 40, :maxlength => 500 %>
        </div>
      </fieldset>
      <p>
      <div class="form_row">
        <%= form.submit 'Create' %>
      </div>
      </p>
    </form>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testps2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>